### ISSUE TITLE
  File "mailfail.py", line 8, in <module>     import colorama

### ISSUE THREAD

**Issue by applslsloidsaihdd** [m0rtem/MailFail#2]
hi
when i execute 
 **sudo python3 mailfail.py --target example@example.com --tor**
i get this error but i already have colorama installed
**Traceback (most recent call last):
  File "mailfail.py", line 8, in <module>
    import colorama
ImportError: No module named 'colorama'**

wtf should i do now. this shitty python 3 my god
i use kali linux 2017.2

**Comment by m0rtem** [comment]
you have definitely run sudo pip3 install colorama?

or you could just remove colorama instances in code... python3 isn't shitty...

**Comment by applslsloidsaihdd** [comment]
alright alright. i tried it in ubuntu linux and it worked just fine.
but now I tried it in parrot os and i get the following error:
[13:15:56] Target email: target@example.sk
[13:15:56] Reason: PySocks doesn't support IPv6

after this the program stops working.
what can I do?

**Comment by m0rtem** [comment]
Hmm OK thank you for bringing this to my attention, I have not tested on Parrot OS before but I will run some tests later and see if I can get that working for ya.
